# Generated by Django 3.2.8 on 2021-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('model', models.CharField(blank=True, max_length=2000, null=True)),
                ('trim', models.CharField(blank=True, max_length=2000, null=True)),
                ('fuel', models.CharField(blank=True, max_length=2000, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('photo', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'warehouse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=2000, null=True)),
                ('trim', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, max_length=20, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('photo', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'warehouse1',
                'managed': False,
            },
        ),
    ]
