# Generated by Django 3.2.8 on 2021-11-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_search'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='search',
            table='search',
        ),
    ]
