# Generated by Django 3.2.9 on 2021-11-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_search_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(blank=True, max_length=2000, null=True)),
                ('model', models.CharField(blank=True, max_length=2000, null=True)),
                ('trim', models.CharField(blank=True, max_length=2000, null=True)),
                ('fuel', models.CharField(blank=True, max_length=2000, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=2000, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('photo', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'encar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Kcar',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=2000, null=True)),
                ('trim', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, max_length=20, null=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('photo', models.CharField(blank=True, max_length=2000, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('accident', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Kcar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=2000, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=2000, null=True)),
                ('media', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'news',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
        migrations.DeleteModel(
            name='Warehouse1',
        ),
    ]
